version: '3.6'

services:
  postgres:
    container_name: postgres_cccat16
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"